-- Jason Tieu
-- 304047667

DROP TABLE IF EXISTS Item;
-- DROP TABLE IF EXISTS ItemCoordinates; -- UNUSED TABLE --
-- DROP TABLE IF EXISTS CoordinatesLocation; -- UNUSED TABLE -- 
DROP TABLE IF EXISTS ItemCategory;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Bid;