LOAD DATA LOCAL INFILE 'nodupItem.dat' INTO TABLE Item
	FIELDS TERMINATED BY '|*|'
	LINES TERMINATED BY '\n';
	
-- UNUSED TABLE --
-- LOAD DATA LOCAL INFILE 'nodupItemCoordinates.dat' INTO TABLE ItemCoordinates
--	FIELDS TERMINATED BY '|*|'
--	LINES TERMINATED BY '\n';

-- UNUSED TABLE
-- LOAD DATA LOCAL INFILE 'nodupCoordinatesLocation.dat' INTO TABLE CoordinatesLocation
--	FIELDS TERMINATED BY '|*|'
--	LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'nodupItemCategory.dat' INTO TABLE ItemCategory
	FIELDS TERMINATED BY '|*|'
	LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'nodupUser.dat' INTO TABLE User
	FIELDS TERMINATED BY '|*|'
	LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'nodupBid.dat' INTO TABLE Bid
	FIELDS TERMINATED BY '|*|'
	LINES TERMINATED BY '\n';